### ISSUE TITLE
Java.lang.IllegalArgumentException: Requirement failed

### ISSUE THREAD

**Issue by BSharifa** [arguslab/Argus-SAF#2]
Hi, 
I have added the picture of the error I have got. The link is below:
https://www.dropbox.com/s/6p2zsl497was1fy/error.png?dl=0

Thank you.

Regards

Sharifa

**Comment by fgwei** [comment]
You can send me the .errorlog which contains the full call stack.

**Comment by BSharifa** [comment]
Hi Professor Wei,

Here is the .errorlog file. Shall I add it in Github? Or this is fine.

Thank you.

Regards
Sharifa

**Comment by fgwei** [comment]
Hi Sharifa,

I am not a professor :P
You can paste all the content in the .errorlog file here.

best,

**Comment by BSharifa** [comment]
Hi Wei,

I thought that. But its fine :) here is the content in that file.

An error occured on 20160708-151554
com.google.common.util.concurrent.UncheckedExecutionException:
java.lang.IllegalArgumentException: requirement failed: JawaClass should be
object type, but get: int
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
at
com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
at
org.sireum.jawa.JawaClassLoadManager$class.getClassOrResolve(JawaClassLoadManager.scala:162)
at org.sireum.jawa.Global.getClassOrResolve(Global.scala:24)
at
org.sireum.jawa.JawaClassLoadManager$$anonfun$resolveAllApplicationClasses$1.apply(JawaClassLoadManager.scala:126)
at
org.sireum.jawa.JawaClassLoadManager$$anonfun$resolveAllApplicationClasses$1.apply(JawaClassLoadManager.scala:124)
at
scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
at
scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
at
scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
at
org.sireum.jawa.JawaClassLoadManager$class.resolveAllApplicationClasses(JawaClassLoadManager.scala:124)
at org.sireum.jawa.Global.resolveAllApplicationClasses(Global.scala:24)
at
org.sireum.jawa.alir.reachability.SignatureBasedCallGraph$.build(SignatureBasedCallGraph.scala:30)
at
org.sireum.jawa.alir.reachability.SignatureBasedCallGraph$.apply(SignatureBasedCallGraph.scala:25)
at
org.sireum.jawa.alir.reachability.ReachabilityAnalysis$.getReachableMethodsBySBCG(ReachabilityAnalysis.scala:34)
at
org.sireum.amandroid.appInfo.ReachableInfoCollector$$anonfun$init$1.apply(ReachableInfoCollector.scala:75)
at
org.sireum.amandroid.appInfo.ReachableInfoCollector$$anonfun$init$1.apply(ReachableInfoCollector.scala:73)
at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
at
org.sireum.amandroid.appInfo.ReachableInfoCollector.init(ReachableInfoCollector.scala:73)
at
org.sireum.amandroid.appInfo.AppInfoCollector$.reachabilityAnalysis(AppInfoCollector.scala:148)
at
org.sireum.amandroid.appInfo.AppInfoCollector$.collectInfo(AppInfoCollector.scala:214)
at
org.sireum.amandroid.alir.componentSummary.ApkYard.loadApk(ApkYard.scala:48)
at
org.sireum.amandroid.security.TaintAnalysisTask.run(TaintAnalysisTask.scala:34)
at
org.sireum.amandroid.cli.TaintAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:119)
at
org.sireum.amandroid.cli.TaintAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:110)
at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
at
org.sireum.amandroid.cli.TaintAnalysis$.taintAnalyze(TaintAnalysis.scala:110)
at org.sireum.amandroid.cli.TaintAnalysis$.main(TaintAnalysis.scala:91)
at org.sireum.amandroid.cli.TaintAnalysis.main(TaintAnalysis.scala)
Caused by: java.lang.IllegalArgumentException: requirement failed:
JawaClass should be object type, but get: int
at scala.Predef$.require(Predef.scala:219)
at org.sireum.jawa.JawaClass.<init>(JawaClass.scala:32)
at
org.sireum.jawa.JawaResolver$class.resolveFromMyClass(JawaResolver.scala:212)
at org.sireum.jawa.Global.resolveFromMyClass(Global.scala:24)
at
org.sireum.jawa.JawaResolver$class.forceResolveToHierarchy(JawaResolver.scala:148)
at org.sireum.jawa.JawaResolver$class.resolveClass(JawaResolver.scala:111)
at org.sireum.jawa.Global.resolveClass(Global.scala:24)
at
org.sireum.jawa.JawaResolver$class.resolveToHierarchy(JawaResolver.scala:136)
at org.sireum.jawa.Global.resolveToHierarchy(Global.scala:24)
at
org.sireum.jawa.JawaClassLoadManager$$anon$1.load(JawaClassLoadManager.scala:137)
at
org.sireum.jawa.JawaClassLoadManager$$anon$1.load(JawaClassLoadManager.scala:132)
at
com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
at
com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
... 33 more

Regards
Sharifa

**Comment by fgwei** [comment]
I just fixed this issue. It caused by rename obfuscation which renames the java class to java primitive name, like, MyClass -> int.
