### ISSUE TITLE
loadApk error, could not find procedure

### ISSUE THREAD

**Issue by mkucijan** [arguslab/Argus-SAF#22]
Same error on several applications. 
`Exception in thread "main" java.lang.RuntimeException: Could not find procedure: chars:()Ljava/util/stream/IntStream;
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.getMethodFromHierarchy(ReachableInfoCollector.scala:312)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$analyzeClassInterfaceCallbacks$2(ReachableInfoCollector.scala:284)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$analyzeClassInterfaceCallbacks$1(ReachableInfoCollector.scala:283)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$analyzeClassInterfaceCallbacks$1$adapted(ReachableInfoCollector.scala:281)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.analyzeClassInterfaceCallbacks(ReachableInfoCollector.scala:281)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.analyzeClass(ReachableInfoCollector.scala:262)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$analyzeMethodForCallbackRegistrations$4(ReachableInfoCollector.scala:252)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$analyzeMethodForCallbackRegistrations$4$adapted(ReachableInfoCollector.scala:251)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.analyzeMethodForCallbackRegistrations(ReachableInfoCollector.scala:251)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$analyzeReachableMethods$1(ReachableInfoCollector.scala:224)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$analyzeReachableMethods$1$adapted(ReachableInfoCollector.scala:223)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.analyzeReachableMethods(ReachableInfoCollector.scala:223)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$collectCallbackMethodsInAppSource$1(ReachableInfoCollector.scala:136)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.$anonfun$collectCallbackMethodsInAppSource$1$adapted(ReachableInfoCollector.scala:135)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:225)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:432)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:432)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.collectCallbackMethodsInAppSource(ReachableInfoCollector.scala:135)
	at org.argus.amandroid.core.appInfo.ReachableInfoCollector.collectCallbackMethods(ReachableInfoCollector.scala:98)
	at org.argus.amandroid.core.appInfo.AppInfoCollector$.analyzeCallback(AppInfoCollector.scala:77)
	at org.argus.amandroid.core.appInfo.AppInfoCollector$.collectInfo(AppInfoCollector.scala:218)
	at org.argus.amandroid.alir.componentSummary.ApkYard.loadApk(ApkYard.scala:39)`

**Comment by fgwei** [comment]
I also get this exception for some apps. I will fix it in next release.

**Comment by mkucijan** [comment]
Thanks for the fast reply!
