### ISSUE TITLE
Running Amandroid

### ISSUE THREAD

**Issue by younkyul** [arguslab/Argus-SAF#5]
I have downloaded the 'Argus-SAF CLI tool' and checked it run well.
I'm trying to run Amandroid on my sample apps, but could not find any instruction for using the functionality.
Could you help me to analyze my apps using Amandroid?

**Comment by fgwei** [comment]
What functionality you want to use to analyze your apps

**Comment by younkyul** [comment]
Security analysis such as data leak, and data injection.

**Comment by fgwei** [comment]
java -jar argus-saf_***-version-assembly.jar
this will give you all the command, like taint for taint analysis, data leak and data injection should be options for that.

**Comment by fgwei** [comment]
java -jar argus-saf_***-version-assembly.jar taint -o /your_output_dir /home/apk_dir
This will run DATA_LEAKAGE for your apps under apk_dir.
You can change the module by   -mo INTENT_INJECTION

If you give a dir it will analyze all apks inside, if you just give an apk, it will analyze that apk.

The command line version does not able to do inter-apk analysis, but there are code in the Argus-SAF can do such thing.

**Comment by younkyul** [comment]
I ran the tool and got an error as follows:

youn@ubuntu:~/Downloads$ java -jar argus-saf_2.11-1.0.5-assembly.jar taint -o ~/home/youn/output/ ~/home/youn/Y_Amazed.apk
Argus-SAF v1.0.5 - a static analysis framework for Android apks
Copyright 2016 Argus Laboratory, University of South Florida

Available Modes:
  a[picheck]    Detecting API misuse.
  d[ecompile]   Decompile Apk file(s).
  s[tage]       Stage middle results.
  t[aint]       Perform taint analysis on Apk(s).

usage: <options>
    --version   Prints the version then exits.
For additional info, see: http://amandroid.sireum.org/
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/sireum/util/FileUtil$ : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.argus.amandroid.core.AndroidGlobalConfig$.checkAmandroidHome(AndroidGlobalConfig.scala:43)
	at org.argus.amandroid.core.AndroidGlobalConfig$.<init>(AndroidGlobalConfig.scala:31)
	at org.argus.amandroid.core.AndroidGlobalConfig$.<clinit>(AndroidGlobalConfig.scala)
	at org.argus.saf.cli.TaintAnalysis$.apply(TaintAnalysis.scala:31)
	at org.argus.saf.Main$.org$argus$saf$Main$$cmdTaintAnalysis(Main.scala:243)
	at org.argus.saf.Main$$anonfun$1.apply(Main.scala:157)
	at org.argus.saf.Main$$anonfun$1.apply(Main.scala:151)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.argus.saf.Main$.delayedEndpoint$org$argus$saf$Main$1(Main.scala:151)
	at org.argus.saf.Main$delayedInit$body.apply(Main.scala:21)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.argus.saf.Main$.main(Main.scala:21)
	at org.argus.saf.Main.main(Main.scala)

==============================================
Also, could you simply let me know how to use the functionality for inter-apk analysis?

**Comment by fgwei** [comment]
Are you running it using java 8?

For using inter-apk analysis functionality, you should know the inner design of Argus-SAF, and write your own program to leveraging Argus-SAF apis to do the analysis.
