### ISSUE TITLE
Caused by: java.io.FileNotFoundException: /root/.amandroid_stash/amandroid/config.ini (No such file or directory)

### ISSUE THREAD

**Issue by xiaoxiaotu** [arguslab/Argus-SAF#50]
amandroid_stash/amandroid/config.ini
Where did this file come from ?

Caused by: java.io.FileNotFoundException: /root/.amandroid_stash/amandroid/config.ini (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at java.net.URL.openStream(URL.java:1038)
        at org.ini4j.spi.IniSource.<init>(IniSource.java:55)
        at org.ini4j.spi.AbstractParser.newIniSource(AbstractParser.java:68)
        at org.ini4j.spi.IniParser.parse(IniParser.java:67)
        at org.ini4j.Ini.load(Ini.java:119)
        at org.ini4j.Ini.load(Ini.java:114)
        at org.ini4j.Ini.load(Ini.java:99)
        at org.ini4j.Wini.<init>(Wini.java:49)
        at org.argus.amandroid.core.AmandroidSettings.<init>(AmandroidSettings.scala:35)
        at org.argus.amandroid.core.AndroidGlobalConfig$.<init>(AndroidGlobalConfig.scala:37)
        at org.argus.amandroid.core.AndroidGlobalConfig$.<clinit>(AndroidGlobalConfig.scala)

**Comment by fgwei** [comment]
It should be automatically downloaded when you first time run Argus-SAF

**Comment by beyondgjc** [comment]
Sorry, but when I run it, it doesn't download automatically. Whether the address is still available？

Could not connect to update site.

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.argus.amandroid.core.decompile.DecompileStrategy$.apply$default$2(DecompilerSettings.scala:41)
	at org.argus.play.tutorial.LoadApk$.main(LoadApk.scala:25)
	at org.argus.play.tutorial.LoadApk.main(LoadApk.scala)
Caused by: java.io.FileNotFoundException: C:\Users\beyon\.amandroid_stash\amandroid\config.ini (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1067)
	at org.ini4j.spi.IniSource.<init>(IniSource.java:55)
	at org.ini4j.spi.AbstractParser.newIniSource(AbstractParser.java:68)
	at org.ini4j.spi.IniParser.parse(IniParser.java:67)
	at org.ini4j.Ini.load(Ini.java:119)
	at org.ini4j.Ini.load(Ini.java:114)
	at org.ini4j.Ini.load(Ini.java:99)
	at org.ini4j.Wini.<init>(Wini.java:49)
	at org.argus.amandroid.core.AmandroidSettings.<init>(AmandroidSettings.scala:35)
	at org.argus.amandroid.core.AndroidGlobalConfig$.<init>(AndroidGlobalConfig.scala:37)
	at org.argus.amandroid.core.AndroidGlobalConfig$.<clinit>(AndroidGlobalConfig.scala)
	... 3 more
