### ISSUE TITLE
AppData.stg not found

### ISSUE THREAD

**Issue by windflyer** [arguslab/Argus-SAF#6]
`DataCollector` initiates a STGroupFile object but the file AppData.stg cannot be found.

    object DataCollector {
        private val template = new STGroupFile("org/sireum/amandroid/alir/resources/dataRecorder/AppData.stg")
         ....
    }

> An error occured on 20160808-103141
java.lang.ExceptionInInitializerError
	at org.argus.amandroid.plugin.TaintAnalysisTask.run(TaintAnalysisTask.scala:59)
	at org.argus.saf.cli.TaintAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:69)
	at org.argus.saf.cli.TaintAnalysis$$anonfun$taintAnalyze$1.apply(TaintAnalysis.scala:60)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at org.argus.saf.cli.TaintAnalysis$.taintAnalyze(TaintAnalysis.scala:59)
	at org.argus.saf.cli.TaintAnalysis$.apply(TaintAnalysis.scala:47)
	at org.argus.saf.Main$.org$argus$saf$Main$$cmdTaintAnalysis(Main.scala:243)
	at org.argus.saf.Main$$anonfun$1.apply(Main.scala:157)
	at org.argus.saf.Main$$anonfun$1.apply(Main.scala:151)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.argus.saf.Main$.delayedEndpoint$org$argus$saf$Main$1(Main.scala:151)
	at org.argus.saf.Main$delayedInit$body.apply(Main.scala:21)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.argus.saf.Main$.main(Main.scala:21)
	at org.argus.saf.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalArgumentException: No such group file: org/sireum/amandroid/alir/resources/dataRecorder/AppData.stg
	at org.stringtemplate.v4.STGroupFile.<init>(STGroupFile.java:69)
	at org.stringtemplate.v4.STGroupFile.<init>(STGroupFile.java:48)
	at org.argus.amandroid.alir.dataRecorder.DataCollector$.<init>(DataCollector.scala:38)
	at org.argus.amandroid.alir.dataRecorder.DataCollector$.<clinit>(DataCollector.scala)
	... 27 more

**Comment by fgwei** [comment]
Yeah, I forget to put it there. Just updated.
